 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
 <html lang="en">
 <head>
     <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
     <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
     <title>Yaf 首页</title>
     <style type="text/css">
     html,body{ margin:0; padding: 0 }
        .main { width: 600px;  margin: 30px auto }
    </style>
</head>
<body>
    <div style="background: #ccc; border: 1px solid #ccc; padding: 10px;">
        <div class="main">
          <h1>Yaf 首页</h1>
          <p>欢迎来到Yaf中心</p>
      </div>
  </div>
  <div class="main">
    <div><? echo $list;?></div>
      <form class="form-horizontal" style="margin-top: 50px;" method="post">
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">登录密码</label>
            <div class="col-sm-10">
                <input type="password" name="password" class="form-control" id="inputPassword3" placeholder="Password">
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">确定登录</button></div>
            </div>
        </form>
    </div>
</body>
</html>
