 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
 <html lang="en">
 <head>
     <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
     <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css">
     <title>Yaf Model</title>
     <style type="text/css">
     html,body{ margin:0; padding: 0 }
        .main { width: 600px;  margin: 30px auto }
    </style>
</head>
<body>
    Models  View
</body>
</html>
